name: GenerateReport

on:
  workflow_dispatch:
    inputs:
      folder_name:
             description: 'selected_folder:'
             required: true
             default: ""
      region_number:
             description: 'Region_number:'
             required: true
             default: ""
      implant_number:
             description: 'Nun_of_implants:'
             required: true
             default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run python code
      run: |
        echo "Your name is: ${{ github.event.inputs.folder_name}}"
        python index.py -f ${{github.event.inputs.folder_name}} -rn ${{github.event.inputs.region_number}} -im ${{github.event.inputs.implant_number}}
